sonar.organization=teslo-shop
sonar.projectKey=teslo-shop
sonar.projectName=Teslo Shop Angular 21
sonar.sources=src
sonar.exclusions=**/*.spec.ts,node_modules/**,dist/**
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/teslo-shop/lcov.info
