sonar.organization=teslo-shop
sonar.projectKey=teslo-shop-angular21
sonar.projectName=Teslo Shop Angular 21
sonar.sources=src
sonar.exclusions=**/*.spec.ts,node_modules/**,dist/**
sonar.clover.reportPath=coverage/teslo-shop/clover.xml
sonar.sourceEncoding=UTF-8
